name: ingenious_test
description: Ingenious Lab Test App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^3.0.1
  logging: ^1.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.0-nullsafety.1
  flutter_bloc: ^7.1.0
  flutter_modular: ^3.3.1
  dio: ^4.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  flutter_profile_picture: ^2.0.0
  search_highlight_text: ^1.0.0+2
  flutter_launcher_icons: ^0.13.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/json/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

